### PR TITLE
Securely encrypt flash cookie to prevent javascript attack

### PR DESCRIPTION
**Pull request by 6543**
source: https://gitea.com/macaron/session/pulls/17

### CODE REVIEW

**Comment by 6543** [comment]
@unknwon do you have questions about this pull ?

**Comment by unknwon** [comment]
Thanks for the PR, but I think we're trying to solve the problem in the wrong layer. Isn't setting cookie to be `httpOnly` enough?

**Comment by silverwind** [comment]
JavaScript (`window.cookie`) and middleboxes can still set this cookie which macaron would happily accept if not encrypted causing the next page to flash that message. It's a rather theoretical attack, thought.

**Comment by unknwon** [comment]
> JavaScript (`window.cookie`) and middleboxes can still set this cookie which macaron would happily accept if not encrypted causing the next page to flash that message. It's a rather theoretical attack, thought.

I see 🤔 ... But I think the real fix is to stop storing flash message in the cookie but in the whatever backend the session relies on. Do you agree?

**Comment by 6543** [comment]
> the real fix is to stop storing flash message

whould't this be a breaking change?

**Comment by unknwon** [comment]
> > the real fix is to stop storing flash message
> 
> whould't this be a breaking change?

Why it's a break change? We're just storing one more key-value pair in the session store, and flash message only appears once. By the time the user sees it, it's gone.

**Pull request closed without merging**
